---
apiVersion: v1
kind: Template
metadata:
  name: sentry-clickhouse
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: clickhouse-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: gp2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      sentry-component: snuba
      service: sentry
    name: clickhouse
  spec:
    replicas: 1
    selector:
      matchLabels:
        sentry-task: clickhouse
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          sentry-task: clickhouse
      spec:
        containers:
        - name: clickhouse-server
          image: ${CLICKHOUSE_IMAGE}:${CLICKHOUSE_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8123
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - name: clickhouse-config
            mountPath: /etc/clickhouse-server/config.d
          - name: clickhouse-data
            mountPath: /var/lib/clickhouse
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        volumes:
        - name: clickhouse-config
          configMap:
            name: ${CLICKHOUSE_CONFIG_CONFIGMAP}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: ${SERVICE_ACCOUNT}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      sentry-component: snuba
      service: sentry
    name: ${CLICKHOUSE_SERVICE}
  spec:
    type: ClusterIP
    ports:
    - port: ${{CLICKHOUSE_SERVICE_PORT}}
      protocol: TCP
      targetPort: 8123
    selector:
      sentry-task: clickhouse
    sessionAffinity: None
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      sentry-component: snuba
      service: sentry
    name: ${CLICKHOUSE_CONFIG_CONFIGMAP}
  data:
    sentry.xml: |
      <yandex>
          <listen_host>0.0.0.0</listen_host>
          <listen_try>1</listen_try>
          <logger>
              <level>information</level>
              <console>1</console>
          </logger>
          <merge_tree>
              <enable_mixed_granularity_parts>1</enable_mixed_granularity_parts>
          </merge_tree>
      </yandex>
parameters:
- name: CLICKHOUSE_IMAGE
  value: yandex/clickhouse-server
  displayName: clickhouse image
  description: clickhouse image
- name: CLICKHOUSE_IMAGE_TAG
  value: 20.3.9.70
  displayName: clickhouse image tag
  description: tag for the clickhouse image
- name: CLICKHOUSE_SERVICE
  value: clickhouse
  displayName: clickhouse service name
  description: name of the clickhouse service
- name: CLICKHOUSE_SERVICE_PORT
  value: "8123"
  displayName: clickhouse service port
  description: port the clickhouse service listens on for connections
- name: CLICKHOUSE_CONFIG_CONFIGMAP
  value: clickhouse
  displayName: clickhouse config map name
  description: name of the config map containing the configuration for clickhouse
- name: SERVICE_ACCOUNT
  value: sentry
  deplayName: sentry service account
  description: name of the service account to use when deploying the pod
