---
apiVersion: v1
kind: Template
metadata:
  name: sentry-init
objects:
- kind: Job
  apiVersion: batch/v1
  metadata:
    # Initializes database with Sentry data and creates initial user
    name: sentry-init
  spec:
    template:
      spec:
        containers:
          - name: database-populator
            image: ${IMAGE}:${IMAGE_TAG}
            resources:
              limits:
                # for some reason this populator is consuming lots of memory
                cpu: 500m
                memory: 1500Mi
              requests:
                cpu: 50m
                memory: 800Mi
            env:
            - name: SENTRY_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: sentry-rds
                  key: db.host
            - name: SENTRY_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: sentry-rds
                  key: db.port
            - name: SENTRY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: sentry-rds
                  key: db.user
            - name: SENTRY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentry-rds
                  key: db.password
            - name: SENTRY_DB_NAME
              value: "sentry"
            - name: SENTRY_EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: server
            - name: SENTRY_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: username
            - name: SENTRY_EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: password
            - name: SENTRY_EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: port
            - name: SENTRY_EMAIL_USE_TLS
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: require_tls
            envFrom:
            - configMapRef:
                name: sentry
            - secretRef:
                name: sentry-general
            - secretRef:
                name: sentry-init
            command:
              - "/bin/bash"
              - "-ecx"
              - |
                # Init migrations
                sentry upgrade --noinput
                # Create user to sentry
                sentry createuser --email ${SENTRY_INITIAL_EMAIL} --password ${SENTRY_INITIAL_PASSWORD} --superuser --no-input
            imagePullPolicy: Always
        restartPolicy: OnFailure
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
parameters:
- name: IMAGE
  value: quay.io/app-sre/sentry
  displayName: senter image
  description: senter docker image. Defaults to quay.io/app-sre/sentry
- name: IMAGE_TAG
  value: latest
  displayName: sentry version
  description: sentry version which defaults to latest
