---
apiVersion: v1
kind: Template
metadata:
  name: sentry
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_ACCOUNT}
  imagePullSecrets:
    - name: quay.io
- apiVersion: v1
  data:
    SENTRY_SINGLE_ORGANIZATION: "${SENTRY_SINGLE_ORGANIZATION}"
  kind: ConfigMap
  metadata:
    labels:
      service: sentry
    name: sentry
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      sentry-component: redis
      service: sentry
    name: redis
  spec:
    replicas: 1
    selector:
      matchLabels:
        sentry-component: redis
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          sentry-component: redis
      spec:
        containers:
        - name: redis
          image: quay.io/app-sre/redis-5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          ports:
          - containerPort: 6379
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 2048Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: ${SERVICE_ACCOUNT}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      sentry-component: sentry-cron
      service: sentry
    name: sentry-cron
  spec:
    replicas: 1
    selector:
      matchLabels:
        sentry-component: sentry-cron
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          sentry-component: sentry-cron
      spec:
        containers:
        - name: sentry-cron
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          command:
          - sentry
          - run
          - cron
          env:
          - name: SENTRY_POSTGRES_HOST
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.host
          - name: SENTRY_POSTGRES_PORT
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.port
          - name: SENTRY_DB_USER
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.user
          - name: SENTRY_DB_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.password
          - name: SENTRY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: sentry-rds
                key: db.name
          - name: SENTRY_EMAIL_HOST
            valueFrom:
              secretKeyRef:
                name: smtp
                key: server
          - name: SENTRY_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smtp
                key: password
          - name: SENTRY_EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: smtp
                key: username
          - name: SENTRY_EMAIL_PORT
            valueFrom:
              secretKeyRef:
                name: smtp
                key: port
          - name: SENTRY_EMAIL_USE_TLS
            valueFrom:
              secretKeyRef:
                name: smtp
                key: require_tls
          envFrom:
          - configMapRef:
              name: sentry
          - secretRef:
              name: sentry-github-oauth
          - secretRef:
              name: sentry-general
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: ${SERVICE_ACCOUNT}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      sentry-component: sentry-web
      service: sentry
    name: sentry-web
  spec:
    replicas: 2
    selector:
      matchLabels:
        sentry-component: sentry-web
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          sentry-component: sentry-web
      spec:
        containers:
        - name: sentry-web
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          command:
          - sentry
          - run
          - web
          env:
          - name: SENTRY_POSTGRES_HOST
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.host
          - name: SENTRY_POSTGRES_PORT
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.port
          - name: SENTRY_DB_USER
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.user
          - name: SENTRY_DB_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.password
          - name: SENTRY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: sentry-rds
                key: db.name
          - name: SENTRY_EMAIL_HOST
            valueFrom:
              secretKeyRef:
                name: smtp
                key: server
          - name: SENTRY_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smtp
                key: password
          - name: SENTRY_EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: smtp
                key: username
          - name: SENTRY_EMAIL_PORT
            valueFrom:
              secretKeyRef:
                name: smtp
                key: port
          - name: SENTRY_EMAIL_USE_TLS
            valueFrom:
              secretKeyRef:
                name: smtp
                key: require_tls
          envFrom:
          - configMapRef:
              name: sentry
          - secretRef:
              name: sentry-github-oauth
          - secretRef:
              name: sentry-general
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: ${SERVICE_ACCOUNT}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      sentry-component: sentry-worker
      service: sentry
    name: sentry-worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        sentry-component: sentry-worker
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          sentry-component: sentry-worker
      spec:
        containers:
        - name: sentry-worker
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          command:
          - sentry
          - run
          - worker
          env:
          - name: SENTRY_POSTGRES_HOST
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.host
          - name: SENTRY_POSTGRES_PORT
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.port
          - name: SENTRY_DB_USER
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.user
          - name: SENTRY_DB_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: sentry-rds
                 key: db.password
          - name: SENTRY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: sentry-rds
                key: db.name
          - name: SENTRY_EMAIL_HOST
            valueFrom:
              secretKeyRef:
                name: smtp
                key: server
          - name: SENTRY_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smtp
                key: password
          - name: SENTRY_EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: smtp
                key: username
          - name: SENTRY_EMAIL_PORT
            valueFrom:
              secretKeyRef:
                name: smtp
                key: port
          - name: SENTRY_EMAIL_USE_TLS
            valueFrom:
              secretKeyRef:
                name: smtp
                key: require_tls
          - name: C_FORCE_ROOT
            value: "TRUE"
          envFrom:
          - configMapRef:
              name: sentry
          - secretRef:
              name: sentry-github-oauth
          - secretRef:
              name: sentry-general
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: ${SERVICE_ACCOUNT}
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    labels:
      sentry-component: sentry-cleanup
      service: sentry
    name: sentry-cleanup
  spec:
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 1
    schedule: "0 0 * * *"
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              sentry-component: sentry-cleanup
          spec:
            containers:
            - name: sentry-cleanup
              image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always
              command:
              - sentry
              - cleanup
              - --days=${CLEANUP_DAYS}
              env:
              - name: SENTRY_POSTGRES_HOST
                valueFrom:
                   secretKeyRef:
                     name: sentry-rds
                     key: db.host
              - name: SENTRY_POSTGRES_PORT
                valueFrom:
                   secretKeyRef:
                     name: sentry-rds
                     key: db.port
              - name: SENTRY_DB_USER
                valueFrom:
                   secretKeyRef:
                     name: sentry-rds
                     key: db.user
              - name: SENTRY_DB_PASSWORD
                valueFrom:
                   secretKeyRef:
                     name: sentry-rds
                     key: db.password
              - name: SENTRY_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: sentry-rds
                    key: db.name
              - name: SENTRY_EMAIL_HOST
                valueFrom:
                  secretKeyRef:
                    name: smtp
                    key: server
              - name: SENTRY_EMAIL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: smtp
                    key: password
              - name: SENTRY_EMAIL_USER
                valueFrom:
                  secretKeyRef:
                    name: smtp
                    key: username
              - name: SENTRY_EMAIL_PORT
                valueFrom:
                  secretKeyRef:
                    name: smtp
                    key: port
              - name: SENTRY_EMAIL_USE_TLS
                valueFrom:
                  secretKeyRef:
                    name: smtp
                    key: require_tls
              envFrom:
              - configMapRef:
                  name: sentry
              - secretRef:
                  name: sentry-github-oauth
              - secretRef:
                  name: sentry-general
              resources:
                limits:
                  cpu: 1000m
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            serviceAccountName: ${SERVICE_ACCOUNT}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      sentry-component: redis
      service: sentry
    name: redis
  spec:
    type: ClusterIP
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      sentry-component: redis
    sessionAffinity: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      sentry-component: sentry
      service: sentry
    name: sentry
  spec:
    type: ClusterIP
    ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      sentry-component: sentry-web
    sessionAffinity: None
parameters:
- name: IMAGE
  value: quay.io/app-sre/sentry
  displayName: sentry image
  description: sentry docker image. Defaults to quay.io/app-sre/sentry
- name: IMAGE_TAG
  value: "latest"
  displayName: sentry version
  description: sentry version which defaults to latest
- name: CLEANUP_DAYS
  value: "14"
  displayName: sentry cleanup interval
  description: how many days of data should be kept in the sentry database
- name: SERVICE_ACCOUNT
  value: "sentry"
  deplayName: sentry service account
  description: name of the service account to use when deploying the pod
- name: SENTRY_SINGLE_ORGANIZATION
  value: "true"
  deplayName: sentry single organization
  description: should sentry be deployed with a single organization configuration
